[package]
name = "digital_audio_rustation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
augioengine = { path = "../augioengine" }
gui = { path = "../gui" }
wgpu = "0.16.2"
