[package]
name = "digital_audio_rustation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioengine = { path = "./audioengine" }
flo = "0.1.0"
flo_draw = "0.3.1"
flo_canvas = "0.3.1"